apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shop-ingress
spec:
  rules:
  - host: store.myexample.com
    http:
      paths:
      - path: /products
        pathType: Prefix
        backend:
          service:
            name: catalog
            port:
              number: 8080


