apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: store-ingress
  namespace: retail
spec:
  rules:
  - host: store.io
    http:
      paths:
      - path: /products
        pathType: Prefix
        backend:
          service:
            name: products-svc
            port:
              number: 8080
      - path: /orders
        pathType: Prefix
        backend:
          service:
            name: orders-svc
            port:
              number: 9090


