apiVersion: v1
kind: Pod
metadata:
  name: db-pod
spec:
  containers:
    - image: postgres:14
      name: postgres
      volumeMounts:
      - name: config-vol
        mountPath: /etc/postgresql
  volumes:
  - name: config-vol
    configMap:
      name: db-settings
      items:
      - key: postgresql.conf
        path: postgres.conf
