apiVersion: v1
kind: Pod
metadata:
  name: api-pod
spec:
  containers:
    - image: busybox
      name: api-pod
      env:
      - name: DATABASE_HOST
        valueFrom:
          configMapKeyRef:
            name: db-config
            key: db_host
      - name: DATABASE_PORT
        valueFrom:
          configMapKeyRef:
            name: db-config
            key: db_port
      command: ["sleep", "3600"]

